### ISSUE TITLE
Nano amount doesn't get calculated

### ISSUE THREAD

**Issue by danni990** [brainblocks/woocommerce-brainblocks#10]
Hey, 

Thx for your awesome plug-in! 

We have a problem since today. (maybe yesterday)
When you go to checkout, the Nano amount doesn't get calculated and the button is just "loading".

![gvubhijnlkm](https://user-images.githubusercontent.com/36767211/36599166-db30a05c-18ae-11e8-94ca-ac6f278c50b5.jpeg)

Price is in EUR.
Already updated from 1.0.0 to 1.0.2 but nothing has changed.

If you want to try it out yourself:
1) [https://cointrend.de/gruppe-nano/](https://cointrend.de/gruppe-nano/)
2) button "In den Warenkorb" 
3) button "Weiter zur Kasse"
4) scroll down

Plug-in worked for 2 weeks without any problems.

**Comment by schenkty** [comment]
Please give this a try again. We have been dealing with some server issues this week and that has caused this issue.

**Comment by bluepnume** [comment]
Looks like this is working on your site now. Thanks for the report!
