### ISSUE TITLE
Mark orders as 'processing'

### ISSUE THREAD

**Issue by schenkty** [brainblocks/woocommerce-brainblocks#4]
Orders should maybe be marked as 'processing' instead of 'completed'. This would allow stores that ship products to mark as 'completed' after they ship instead of after they have the payment. This could be a setting since it is a preference.

**Comment by schenkty** [comment]
Fixed soonish :)

**Comment by bluepnume** [comment]
Set to `processing` by default. Leaving this open to remind me to make this configurable when I have a spare sec to work on this plugin some more.

**Comment by bluepnume** [comment]
(and published latest to https://brainblocks.io/static/woocommerce-gateway-brainblocks.zip)
