### ISSUE TITLE
Update Plugin

### ISSUE THREAD

**Issue by Mishul-G** [brainblocks/woocommerce-brainblocks#5]
BrainBlocks,

Hi! Just wanted to reach out regarding how to update your plugin on our wordpress website (via woo-commerce). Looking forward to hear back. Thank you.

**Comment by seedsower** [comment]
I was interested too.  I installed it and was going live next month .. Great work by the way.. peace T

**Comment by bluepnume** [comment]
I think the best option for now might just be to uninstall and reinstall the latest version from the zip file. Please let me know if you see any issues doing this.
