### ISSUE TITLE
Orders failing

### ISSUE THREAD

**Issue by MintyWater23** [brainblocks/woocommerce-brainblocks#7]
Hi, 

I'm using Brainblocks at [nanomerch.net](https://nanomerch.net)... most of the orders that we're getting in paid for with nano are coming through as a failed order. The user is not getting confirmation that their order has gone through. In all cases but 1 (please see other issue I'll submit in a second as I feel its a separate issue) the nano has hit my wallet. So its just a case of manually setting the order to processing. 

In woocommerce, I get the following error code (as an example from one today)... 

"Incorrect amount: ‘49.14’ expected ‘51.88’ Order status changed from Pending payment to Failed."

So it seems like its an issue with the USD price changing whilst they're sending...

Any help is hugely appreciated!

Thanks,

Mark

**Comment by bluepnume** [comment]
Can you please:

1. Expose a test item for $0.05, so I can test on your site
2. Share all of the transactions/addresses for the failed orders so I can manually process them

**Comment by schenkty** [comment]
Want to add an update here. @bluepnume looks like when the shipping costs change, the button does not update with the new correct nano amount

**Comment by MintyWater23** [comment]
Chatting with schenkty on discord... seems it is indeed an issue with shipping costs. If a user chooses a different shipping cost, or indeed changes their delivery country and the costs change, the nano price doesnt update...

**Comment by MintyWater23** [comment]
Here are the two transactions from today that have not made it to my wallet... 

5.421000 https://raiblocks.net/block/index.php?h=7754698298B214BB8F6EABABAA0337BC3B4F4137A684DA5023C41A7A1106A687

2.409000 https://raiblocks.net/block/index.php?h=EF6CD1BC465EE0A0133C6CFCB3051397D3682951EA0989E98F1392459E1019A5

**Comment by bluepnume** [comment]
OK, thanks for the details. Looks like those two orders have been auto-refunded. Can you please either cancel those orders, or contact the buyers to ask them to re-send the funds manually?

On the shipping cost, thanks both for spending time to figure that out. I'll look into how the woocommerce plugin can be fixed to account for changing shipping.

Again, really sorry for all of the teething problems here.

**Comment by MintyWater23** [comment]
@bluepnume Thanks! I'll ping the customers and ask if they can send manually :) 

An edit to the plugin to allow shipping updates would be lovely, let me know if you go ahead with that! 

Thanks to you and @schenkty for very quick responses, really appreciated!

**Comment by bluepnume** [comment]
FYI, I've uploaded a new version of this plugin, which includes an option (enabled by default) to do a full-page redirect rather than showing the brainblocks button inline. Would appreciate if you can try this instead if you're still seeing problems, as it should resolve some compatibility issues.

https://brainblocks.io/static/woocommerce-gateway-brainblocks.zip

<img width="771" alt="screen shot 2018-03-11 at 2 46 09 pm" src="https://user-images.githubusercontent.com/1219075/37258846-24668280-253b-11e8-987d-957b6d1f87d3.png">

**Comment by MintyWater23** [comment]
Thanks for the update. Will this fix the shipping value issue? As is, if a
user changes the shipping cost after the checkout page has loaded the nano
value does not change and is therefore incorrect and the order fails
despite the user having sent funds.

Thanks,

Mark



*Mark Boyd*
Managing Director
07843 606 434
0131  <0131+610+8726>285 0900 <07843+606+434>
http://www.transparentdigital.co.uk

Skype: MarkJWBoyd <https://mail.google.com/mail/u/0/#>

100b Constitution Street, Edinburgh, EH6 6AW
<http://www.facebook.com/Transparent-Digital-438983762880893/timeline/>
<http://www.linkedin.com/profile/view?id=AAIAAALkccoBxo6FDAIp9fxIyhpNXexvLcIWSNw&trk=nav_responsive_tab_profile>
  <http://twitter.com/boydy>

**Comment by bluepnume** [comment]
Yes, it should fix that issue. Please let me know if you still see the problem after this update, in full-page mode.
