### ISSUE TITLE
Nano hasnt hit my wallet

### ISSUE THREAD

**Issue by MintyWater23** [brainblocks/woocommerce-brainblocks#8]
Hi, 

I've had an order this morning on [NanoMerch.net](https://nanomerch.net) where the user has paid for the order with Nano and the following has happened...

- The user has not had confirmation of order placed
- I (as the merchant) have received an email stating order failed (which I have seen for some orders as per my [other issue submission](https://github.com/brainblocks/woocommerce-brainblocks/issues/7)) 
- The transaction has gone from the customer to the address they were asked to send to 
- No nano has arrived at our wallet 

here is the tx as provided by the customer - https://raiblocks.net/block/index.php?h=7754698298B214BB8F6EABABAA0337BC3B4F4137A684DA5023C41A7A1106A687

first priority is hopefully to get the nano transferred to our wallet please. second is to work out what has gone wrong here and in our other issue, to ensure it doesnt happen with future orders!

Love the plugin, great work guys :) Hopefully we can get this resolved quickly!

Thanks, 

Mark @ NanoMerch.net

**Comment by MintyWater23** [comment]
I've just submitted a test order paying with Nano, and the order went through just fine, however the nano has not arrived at my wallet... 

Here's the transaction ID https://raiblocks.net/block/index.php?h=EF6CD1BC465EE0A0133C6CFCB3051397D3682951EA0989E98F1392459E1019A5

**Comment by schenkty** [comment]
Hey @MintyWater23 pm me on the nano discord so we can figure this out. username: schenkty

**Comment by schenkty** [comment]
Just to update here. Issue was server related - should be cleared up
