### ISSUE TITLE
Brainblocks not loading for me on any WooCommerce Stores

### ISSUE THREAD

**Issue by hrazzell** [brainblocks/woocommerce-brainblocks#9]
Hi team - the plugin was working for me perfectly yesterday, and without changing anything I woke up today to continue working on my site, however the plugin is throwing errors every time.

The error happens on any browser, incognito doesn't help and and I get the same error on other stores using BrainBlocks on WooCommerce. Have screenshotted the error below:

By the way, thanks for making such an easy to use plugin!!

![image](https://user-images.githubusercontent.com/10492483/36347894-6fd7869a-14b7-11e8-92d7-e642fb5742b3.png)

**Comment by bluepnume** [comment]
Fixed! Coinmarketcap changed their nano->usd api and broke backwards compatibility. Bad timing since I was out all evening. Fixed now though.

**Comment by hrazzell** [comment]
Awesome! Thanks so much :)
